EXTRA_CFLAGS := -I $(TOPDIR)/kernel/include
EXTRA_CFLAGS += -I $(TOPDIR)/arch/riscv/include -I $(TOPDIR)/include
EXTRA_CFLAGS += -I $(TOPDIR)/net/lwip/port/include
EXTRA_CFLAGS += -I $(TOPDIR)/net/lwip/upstream/src/include
obj-y += acd.o autoip.o dhcp.o etharp.o icmp.o igmp.o
obj-y += ip4_frag.o ip4.o ip4_addr.o
