EXTRA_CFLAGS := -I $(TOPDIR)/kernel/include
EXTRA_CFLAGS += -I $(TOPDIR)/arch/riscv/include -I $(TOPDIR)/include
EXTRA_CFLAGS += -I $(TOPDIR)/net/lwip/port/include
EXTRA_CFLAGS += -I $(TOPDIR)/net/lwip/upstream/src/include
obj-y += sys_arch.o netif.o
