EXTRA_CFLAGS := -I ../include -I ../../arch/riscv/include -I ../../include
CFLAGS_file.o := 


obj-y += file.o pipe.o
obj-y += vfs.o char_device.o device.o devfs.o tmpfs.o
obj-y += lwext4/
obj-y += fatfs/
