#ifndef __CAFFEINIX_LWIPOPTS_H
#define __CAFFEINIX_LWIPOPTS_H

#define NO_SYS 0
#define SYS_LIGHTWEIGHT_PROT 1
#define LWIP_TCPIP_CORE_LOCKING 0
#define LWIP_TCPIP_CORE_LOCKING_INPUT 0

#define MEM_ALIGNMENT 8
#define MEM_SIZE (256 * 1024)
#define MEM_OVERFLOW_CHECK 0
#define MEMP_OVERFLOW_CHECK 0
#define MEMP_SANITY_CHECK 1

#define PBUF_POOL_SIZE 64
#define PBUF_POOL_BUFSIZE 1600
#define MEMP_NUM_PBUF 64
#define MEMP_NUM_RAW_PCB 8
#define MEMP_NUM_UDP_PCB 16
#define MEMP_NUM_TCP_PCB 16
#define MEMP_NUM_TCP_PCB_LISTEN 8
#define MEMP_NUM_TCP_SEG 64
#define MEMP_NUM_ARP_QUEUE 16
#define MEMP_NUM_NETBUF 32
#define MEMP_NUM_NETCONN 32
#define MEMP_NUM_TCPIP_MSG_API 32
#define MEMP_NUM_TCPIP_MSG_INPKT 64

#define LWIP_IPV4 1
#define LWIP_IPV6 0
#define LWIP_ARP 1
#define LWIP_ETHERNET 1
#define LWIP_ICMP 1
#define LWIP_RAW 1
#define LWIP_UDP 1
#define LWIP_TCP 1
#define LWIP_DHCP 1
#define LWIP_DHCP_DOES_ACD_CHECK 0
#define LWIP_DNS 1
#define LWIP_IGMP 0
#define IP_SOF_BROADCAST 1

#define LWIP_NETCONN 1
#define LWIP_SOCKET 1
#define LWIP_COMPAT_SOCKETS 0
#define LWIP_POSIX_SOCKETS_IO_NAMES 0
#define LWIP_SOCKET_SELECT 1
#define LWIP_SOCKET_POLL 1
#define LWIP_NETCONN_SEM_PER_THREAD 1
#define LWIP_NETCONN_FULLDUPLEX 1
#define LWIP_SO_RCVTIMEO 1
#define LWIP_SO_SNDTIMEO 1
#define LWIP_SO_RCVBUF 1
#define LWIP_SO_LINGER 1
#define SO_REUSE 1
#define LWIP_FIONREAD_LINUXMODE 1
#define LWIP_NETIF_API 1
#define LWIP_NETIF_HOSTNAME 1
#define LWIP_NETIF_STATUS_CALLBACK 1
#define LWIP_NETIF_LINK_CALLBACK 1
#define LWIP_PROVIDE_ERRNO 1

#define TCP_MSS 1460
#define TCP_WND (8 * TCP_MSS)
#define TCP_SND_BUF (8 * TCP_MSS)
#define TCP_SND_QUEUELEN 32
#define TCP_LISTEN_BACKLOG 1

#define TCPIP_MBOX_SIZE 64
#define DEFAULT_ACCEPTMBOX_SIZE 16
#define TCPIP_THREAD_NAME "tcpip"
#define TCPIP_THREAD_STACKSIZE 0
#define TCPIP_THREAD_PRIO 1
#define DEFAULT_THREAD_STACKSIZE 0
#define DEFAULT_THREAD_PRIO 1

#define LWIP_STATS 1
#define LWIP_DEBUG 0
#define LWIP_CHECKSUM_CTRL_PER_NETIF 0

void lwip_socket_event_notify(void);
#define LWIP_SOCKET_EVENT_NOTIFY() lwip_socket_event_notify()

#endif
