EXTRA_CFLAGS := -I ./include -I ../arch/riscv/include -I ../include 
CFLAGS_file.o := 


obj-y += string.o memrange.o buddy.o palloc.o spinlock.o rbtree.o ktime.o \
timeconv.o \
printk.o thread.o wait.o \
sleeplock.o switchto.o trampoline.o process.o\
plic.o console.o printf.o scheduler.o \
exec.o sysfile.o syscall.o sysproc.o workqueue.o main.o
obj-y += irq/
