EXTRA_CFLAGS := -I ../../../kernel/include
EXTRA_CFLAGS += -I ../../../arch/riscv/include -I ../../../include -I .
EXTRA_CFLAGS += -Wno-sign-compare
EXTRA_LDFLAGS := -T ../../../kernel/kernel.ld

obj-y += fdt.o fdt_ro.o fdt_check.o
