# Early polling console plus normal UART core and NS16550 driver.
EXTRA_CFLAGS := -I ../../../kernel/include \
	-I ../../../arch/riscv/include -I ../../../include
obj-y += earlycon.o uart.o ns16550.o
