# Stack-independent network-device core and its loopback/selftests.
EXTRA_CFLAGS := -I ../../kernel/include -I ../../arch/riscv/include
EXTRA_CFLAGS += -I ../../include
obj-y += device.o loopback.o packet.o selftest.o
